Added a new route for supporting a secondary bucket
crunchyroll/evs-s3helper pull request #27
Opened 2021-07-22 21:31 UTC by som-poddar

- Ad crunchyroll, we would like to extend this utility to support avod streaming in the platform.
- This change adds this capability with the minimal amount of change
to the existing functionality.
- Updated to use aws sdk for s3 get call

2021-07-22 21:36 UTC, rmikhael commented on README.md
> +```
add s3_ad_bucket to the config params example.

2021-07-22 21:36 UTC, mskariah1942 commented
@som-poddar where are the unit tests?

2021-07-22 21:46 UTC, rmikhael approved these changes
+1

2021-07-23 04:41 UTC, mlevkov requested changes

2021-07-23 04:41 UTC, mlevkov commented on main.go
> +	mux.Handle("/avod/", http.HandlerFunc(forwardToS3ForAd))
@som-poddar why are we sticking to the single bucket, it would be better if the route was reflecting a bucket name instead of this "fixed" route. as such, /{bucket Name}/<key.... etc.>

2021-07-23 04:41 UTC, mlevkov commented on s3.go
> +	if len(a) != 2 || a[0] != "127.0.0.1" {
At some point, this needs to change. There is no reason why it has to be "local". Nginx has no such restriction.

2021-07-23 04:41 UTC, mlevkov commented on s3.go
> +	s3url := fmt.Sprintf("http://s3-%s.amazonaws.com/%s%s%s", conf.S3Region, bucket, conf.S3Path, upath)
This is a very expensive operation on every call, try to consider using Join.

2021-07-23 04:41 UTC, mlevkov commented on s3client/get.go
> +	})
why are you making a new session on every call to this function?

2021-07-23 04:41 UTC, mlevkov commented on s3.go
> +	getObject, getErr := s3client.GetObject(conf.S3AdBucket, s3Path, byterange)
calling GetObject with a new session set up on every request might get very expensive and blocking.

2021-07-26 20:25 UTC, som-poddar commented on README.md
> +```
done.

2021-07-26 20:30 UTC, som-poddar commented on s3.go
> +	s3url := fmt.Sprintf("http://s3-%s.amazonaws.com/%s%s%s", conf.S3Region, bucket, conf.S3Path, upath)
Agreed. again, the intent of this PR is to keep the current plumbing for the media route exactly the same while adding support for the ad media route which will use a secondary bucket.

I will address move all performance optimizations to a different PR via new Github issues.

2021-07-26 20:56 UTC, som-poddar commented on s3.go
> +	getObject, getErr := s3client.GetObject(conf.S3AdBucket, s3Path, byterange)
Fair point @mlevkov, I was aware of this limitation but was reluctant to add this in one PR to keep the diff small/manageable. But on second thought, made the changes you suggested via https://github.com/crunchyroll/evs-s3helper/pull/27/commits/ec124ef838e62db0a524285775cf2cfc0c4a08f3.

2021-07-26 20:56 UTC, som-poddar commented on s3client/get.go
> +	})
see my response https://github.com/crunchyroll/evs-s3helper/pull/27#discussion_r676938467

2021-07-26 20:57 UTC, som-poddar commented on s3.go
> +	if len(a) != 2 || a[0] != "127.0.0.1" {
done. Filed https://github.com/crunchyroll/evs-s3helper/issues/29

2021-07-26 21:03 UTC, som-poddar commented on main.go
> +	mux.Handle("/avod/", http.HandlerFunc(forwardToS3ForAd))
@mlevkov, we are not sticking to a single bucket, matter of fact - the purpose of this PR is to introduce a secondary bucket to serve AVOD contents. 

The reason this service exists is to abstract downstream bucket configuration, permissions, etc from the caller. For example, the VoD Nginx packager only needs to know, which route leads to serving ad content and which route leads to serving VoD content.  Anything beyond the route must be abstracted from the packager or upstream caller(s).

2021-07-27 01:43 UTC, mlevkov commented on main.go
> +	mux.Handle("/avod/", http.HandlerFunc(forwardToS3ForAd))
totally understood, but this design is only specific to the "avod" bucket. The consideration should be defined via bucket abstract, which is accessible from Nginx config. If you consider the design I've proposed, then you can easily expose "other" buckets without rewriting the software in the future, whenever we need new buckets to access. This is too much coupling to bucket name and purpose.

2021-07-27 01:48 UTC, mlevkov commented on s3.go
> +	s3url := fmt.Sprintf("http://s3-%s.amazonaws.com/%s%s%s", conf.S3Region, bucket, conf.S3Path, upath)
changing Sprintf to join is not that difficult. How do you know that your "sprintf" call will not create an additional burden on already heavy call-oriented adapter? Have you profiled your code?

2021-07-27 01:49 UTC, mlevkov commented on s3client/get.go
> +	})
I saw that, thanks. Excellent!

2021-07-27 01:53 UTC, mlevkov commented
please consider adding unit tests, positive and negative, even if it is a mocked payload. Please test this thoroughly in Proto0.

2021-08-13 16:33 UTC, mskariah1942 commented
Since this PR is now more than 20 days, are we still waiting to get unit tests in? Let me know if there are concerns or any discussion needed. Thanks!

2021-09-01 20:25 UTC, rmikhael commented on s3.go
> +func forwardToS3(w http.ResponseWriter, r *http.Request, bucket string) {
I know you didn't change that, but shouldn't all 3 "forwardToS3" functions  be methods of App, for consistency?

2021-09-01 22:44 UTC, som-poddar commented on s3.go
> +func forwardToS3(w http.ResponseWriter, r *http.Request, bucket string) {
Noted, perhaps a new issue/pull-req will be a good place for this.

2021-09-02 16:59 UTC, merged